// Generated by CoffeeScript 1.4.0
(function() {
  var loadJSON, url, username;

  username = 'csiszarattila';

  url = "http://www.coderwall.com/" + username + ".json?callback=processJSON";

  loadJSON = function(url) {
    var head, newScript;
    head = document.getElementsByTagName('head')[0];
    newScript = document.createElement('script');
    newScript.type = 'text/javascript';
    newScript.src = url;
    return head.appendChild(newScript);
  };

  window.processJSON = function(results) {
    var badgeSize, element, item, newImage, newLink, _i, _len, _ref;
    element = document.getElementById('coderwall');
    badgeSize = 55;
    _ref = results.data.badges;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      item = _ref[_i];
      newLink = document.createElement('a');
      newLink.href = "http://www.coderwall.com/" + username;
      newImage = document.createElement('img');
      newImage.src = item.badge;
      newImage.title = "" + item.name + ": " + item.description;
      newImage.alt = item.name;
      newImage.height === (newImage.width = badgeSize);
      newLink.appendChild(newImage);
      element.appendChild(newLink);
    }
  };

  loadJSON(url);

}).call(this);
